### ISSUE TITLE
Cannot run the codes via "Shift + enter"

### ISSUE THREAD

**Issue by RanggaPAji** [pndmix/atom-rampcode#1]
First, thank you so much for making this rampcode plugin for atom.

i use Mac when i install the rampcode for Atom.

at first i open the rampcode-060.pd file and then i open the examples.ramp file. When i start the toggle for rampcode it shows an error about pdsend won't spawned and need to put the path manually so i did put the pdsend path like this:

/Applications/Pd-0.49-1.app/Contents/Resources/bin/pdsend

after that i try to start it again and it works!

but, when i try to run the code it just doesn't want to run. so i wonder why, and then i tried to run it from the toolbars to evaluate a line and it works.\

so i couldn't use the Shift + Enter feature and the Option + Enter.

**Comment by pndmix** [comment]
Fixed in version 0.2.1.
Thanks @RanggaPAji , please try it :panda_face:

**Comment by RanggaPAji** [comment]
Now it's working! thanks man!

**Comment by Etol1LC** [comment]
Where do you insert the pd-send path manually?
I am stuck there...

**Comment by RanggaPAji** [comment]
Go to the atom-rampcode packages, and on the Pdsend PATH i put this
/Applications/Pd-0.49-1.app/Contents/Resources/bin/pdsend . Hope this
helps! :D

**Comment by Etol1LC** [comment]
Don't get it! Can you please share an example like step by step. There is
definetley something I am clearly missing... Thanks

Il giorno lun 1 lug 2019 alle 13:32 RanggaPAji <notifications@github.com>
ha scritto:

> Go to the atom-rampcode packages, and on the Pdsend PATH i put this
> /Applications/Pd-0.49-1.app/Contents/Resources/bin/pdsend . Hope this
> helps! :D
>
>

**Comment by RanggaPAji** [comment]
i'm currently using MAC for this, haven't tried it yet with another
operating system

**Comment by Etol1LC** [comment]
Thanks a lot! At the end it was very helpful and it did work!!! Great!
Thanks again!

Il giorno lun 1 lug 2019 alle 18:14 RanggaPAji <notifications@github.com>
ha scritto:

> i'm currently using MAC for this, haven't tried it yet with another
> operating system
>
