### ISSUE TITLE
Suggestion: $v1 snippet and color

### ISSUE THREAD

**Issue by gabochi** [pndmix/atom-rampcode#2]
It would be great to highlight $v1 in a special color since it is a very important word, the only input-variable value.  Also, it could be a snippet for it, like $.

**Comment by pndmix** [comment]
Thx suggestion. In version 0.2.2, it has been added the snippet with $, and changed the highlight color. Also, this snippet isn't supported auto-complete (maybe $ character) but this is enabled with $ + Tab.

**Comment by gabochi** [comment]
Great! Yes, I think is the $ character that maybe is reserved.  Thanks!
