### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by gabochi** [pndmix/atom-rampcode#3]
I've noticed that all spaces are deleted but the ones that follow the `set` and `rec` commands. This is very useful but I want to add some features or arguments to these ones for setting the loop length and sample rate like : `set rate 40000;` , `set loop 8` or `rec file xname`.  How could this be arranged?

**Comment by gabochi** [comment]
I'm still testing some things... maybe the better thing is to reserve a special character for a meant space like `:` in `set:1;` so I can try different commands.

**Comment by pndmix** [comment]
No problem, it is possible to handle a meant space in only this package. The details are in the above commit, that use regular expressions to handle this.
e.g. can be avoided deleting space by replacing a meant space with `@`.

**Comment by gabochi** [comment]
Excelent! That's great. Thanks :)

**Comment by gabochi** [comment]
I have now 0.2.2 but `@` does not work, it is not replaced as a regular space. Sorry :(

**Comment by pndmix** [comment]
Sorry, this feature has not been included in v0.2.2, and `@` character can not be used in expressions, the internal process only.
e.g. when receiving `set 1.25; sin($v1 / 1000);` from the user, this internal process convert to `set@1.25;sin($v1/1000);` and send `set 1.25;sin($v1/1000);` to PD finally.

In addition, I have two ideas about this. Which expression from the user do you like better ? In response to this, release next version. 👀 
- use only space `set rate 40000;`
- use reserved character `set@rate@40000;`

**Comment by gabochi** [comment]
I prefer a reserved character so I can work on different updates and you don't have to update the package all the time. If it could be `:`, it would be great, if not, don't worry, use the one you like the most :D Thanks

**Comment by pndmix** [comment]
Thanks man, I will think about it 😃

**Comment by pndmix** [comment]
@gabochi I updated to use `:` and `@`, use it if you would like 😄

**Comment by gabochi** [comment]
Yes, I realize that and I'm using it already. Thank you so much for doing this package, I'll update more videos with it very soon and I'm already updating the documentation.
